version: '3.8'

services:
  web:
    build: .
    ports:
      - "8080:80"
    volumes:
      - ./client/:/var/www/html
      - ./server/:/var/www/server
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "web_project"
      MYSQL_USER: "user"
      MYSQL_PASSWORD: "public"
    ports:
      - "3307:3306"
    volumes:
      - mydbdata:/var/lib/mysql

volumes:
  mydbdata:
