version: '3.8'
services:
  web:
    image: php:8.0-apache
    ports:
      - "8080:80"
    volumes:
        - ./client/:/var/www/html
        - ./server/:/var/www/server
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "web_project"
      MYSQL_USER: "user"
      MYSQL_PASSWORD: "password"
    ports:
      - "3308:3308"
    volumes:
      - mydbdata:/var/lib/mysql

volumes:
  mydbdata:
